language: node_js
node_js:
  - 8

script:
  - npm test

before_script:
  # XXX this is a fix for nokogiri building on Travis
  - npm run bootstrap

after_success:
  # this will short-circuit the publish step if it fails to interpolate $NPM_API_KEY
  - npm config set "//registry.npmjs.org/:_authToken=\${NPM_API_KEY}"
  - script/after_success
