language: node_js
node_js:
  - 8

before_script:
  # XXX this is a fix for nokogiri building on Travis
  - pushd lib/octicons_helper; bundle config build.nokogiri --use-system-libraries; popd
  - npm run bootstrap
