version: 2
jobs:
  build:
    docker:
      # XXX assume latest, 8.x?
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: bootstrap
          command: script/bootstrap
      - run:
          name: test
          command: npm test
