name: CI
on:
  push:
  pull_request_target:

jobs:
  main:
    name: Main Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: yarn
      - name: Building
        run: yarn build
      - run: cp -r icons lib/build/svg
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test

  octicons_node:
    name: 'npm @primer/octicons'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: yarn
      - name: Building
        run: yarn build
      - run: cp -r icons lib/build/svg
      - run: cd ./lib/octicons_node
      - run: yarn
      - name: Building
        run: yarn build
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
