name: CI
on:
  push:
  pull_request_target:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: yarn
      - name: Building
        run: yarn build
      - run: cp -r icons lib/build/svg
      - uses: actions/upload-artifact@v2
        with:
          name: octicons-build
          path: ./lib/build


  main:
    name: Main project
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: actions/download-artifact@v2
        with:
          name: octicons-build
          path: ./lib/build
      - run: yarn
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test

  octicons_node:
    name: '@primer/octicons'
    needs: build
    runs-on: ubuntu-latest
    defaults:
      env:
        working-directory: ./lib/octicons_node
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: actions/download-artifact@v2
        with:
          name: octicons-build
          path: ./lib/build
      - run: yarn
      - name: Building
        run: yarn build
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test

  octicons_react:
    name: '@primer/octicons-react'
    needs: build
    runs-on: ubuntu-latest
    defaults:
      env:
        working-directory: ./lib/octicons_react
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: actions/download-artifact@v2
        with:
          name: octicons-build
          path: ./lib/build
      - run: yarn
      - name: Building
        run: yarn build
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
