on:
  push:
    paths:
    - 'icons/**'
    - '.github/workflows/optimize.yml'
name: Optimize SVGs
jobs:
  optimize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: npm install
      - run: npm run svgo
      - uses: EndBug/add-and-commit@v4
        with:
          add: 'icons'
          message: 'Optimize SVGs'
          author_email: actions@github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
